version: "3.3"

services:
  letsencrypt-companion:
    restart: always
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: letsencrypt-nginx-proxy-companion
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "../volumes/certs:/etc/nginx/certs:rw"
      - "../volumes/includes:/etc/nginx/vhost.d:rw"
      - nginx_conf:/etc/nginx/conf.d
      - nginx_html:/usr/share/nginx/html
    environment:
      - NGINX_DOCKER_GEN_CONTAINER=nginx-gen
      - NGINX_PROXY_CONTAINER=nginx-frontproxy

